export const SET_CARDS_DATA = 'SET_CARDS_DATA'
export const SET_USERS_BEHAVIOR = 'SET_USERS_BEHAVIOR'
export const SET_EMAIL_STATISTICS = 'SET_EMAIL_STATISTICS'
export const SET_SALES_DATA = 'SET_SALES_DATA'
